# Copyright (c) 2022--2023 TK Chia
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Configuration file for GitLab (https://gitlab.com/) Continuous Integration.

image: ubuntu:jammy
stages:
  - test
test:
  stage: test
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update -y
    - >
        apt-get install -y git make gcc-mingw-w64-x86-64 lld musl-dev
        dosfstools mtools fdisk ccache meson ninja-build qemu-utils zip
  script:
    - ./configure
    - make
  artifacts:
    paths:
      - bootx64.efi
      - hd.img.zip
