# Copyright (c) 2023 TK Chia
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Configuration file for GitHub (https://github.com/) Continuous Integration.

name: ci-build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git make gcc-mingw-w64-x86-64 lld musl-dev \
                                  dosfstools mtools ccache meson ninja-build \
                                  fdisk qemu-utils zip
      - name: build
        run: |
          ./configure
          make
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            bootx64.efi
            hd.img.zip
